### ISSUE TITLE
[SUGGESTION] Ditch QB-Lockpick for ox_lib skillcheck

### ISSUE THREAD

**Issue by menkzy** [Qbox-project/qb-storerobbery#5]
**Is your feature request related to a problem? Please describe.**
qb-lockpick is ugly and very boring to do. ox_lib now has a skillcheck which is nice and optimised and very easy to use

**Describe the feature you'd like**
it's a hot circle minigame that isnt qb-lock or qb-lockpick and optimized and secure

**Describe alternatives you've considered**
qblock which is trash

**Additional context**
[Ox_lib skillcheck docs](https://overextended.github.io/docs/ox_lib/Interface/Client/skillcheck)
https://imgur.com/RWSWZ1I

**Comment by ChatDisabled** [comment]
While I get it, the current lockpick minigame is more realistic in the store robbery sense? Same goes for the vehicles honestly. But `qb-keyminigame` will definitely get ditched.
