### ISSUE TITLE
[SUGGESTION] Make it a robbery

### ISSUE THREAD

**Issue by TonybynMp4** [Qbox-project/qb-storerobbery#6]
idk if im an alien or something but it seems like the store 'robbery' is anything but a store robbery, like idk i never saw a dude enter a 7/11 and start lockpicking the thing,
However entering the store and pointing a gun at the cashier do happen.

anyway im a prick but my suggestion for the lovely lads of QBox would be to make the storerobbery great (again?) by yeeting the lockpicking, instead making the player rob the store.
I think putting a ped that we can target with a rob option (that only works if u have a valid weapon in hands) could be a good way of implementing that?

And instead of a skill based minigame simply put in a progressbar with a randomized time and randomly have the cashier shoot u cauz it's the americas bruv 🔫 🔫 .

I think having the cash be given by spawning a prop and having to target it can be cool,
maybe even having the cashier give smol amounts 💸 💸  of cash multiple times then finally giving a big bag 💰at the end.

The lil vault in the back is cool tho.
🤔

**Comment by ChatDisabled** [comment]
Discussed in private

**Comment by TonybynMp4** [comment]
private UwU
